name: "✨ 새로운 기능"
description: "새로운 기능에 대한 이슈를 작성하세요!"
title: "[새기능] "
labels: "새기능"
body:
  - type: input
    attributes:
      label: ✨ 개요
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 꼼꼼하게 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 해야 할 일
      description: 해야 할 일을 작성해 주세요.
      placeholder: |
        - [ ] 회원가입 API 구현
        - [ ] 회원가입 API 테스트 코드 작성
        - [ ] 회원가입 API 문서화
    validations:
      required: true